#!/usr/bin/env node
/**
 * FieldOps3i — deterministic STATE.md snapshot updater.
 *
 * Replaces what `fieldops-automation-memory-agent` used to do by hand for the
 * mechanical fields: it regenerates the "## Last verified" and "## Branch +
 * commit" sections of automation/STATE.md from live git + index.html, and
 * leaves every narrative section (shipped tables, Supabase notes, open gates)
 * exactly as written. Run it after any deploy / branch sync.
 *
 *   node scripts/update-state.cjs            # rewrite the two mechanical sections
 *   node scripts/update-state.cjs --check    # print what WOULD change, write nothing
 *
 * Narrative/judgment updates (what shipped, Supabase row counts, stale flags)
 * stay manual — edit STATE.md directly for those.
 */
const { execSync } = require('child_process');
const fs   = require('fs');
const path = require('path');

const ROOT       = path.resolve(__dirname, '..');
const STATE_FILE = path.join(ROOT, 'automation/STATE.md');

const sh = (cmd) => execSync(cmd, { cwd: ROOT, encoding: 'utf8' }).trim();
const shSafe = (cmd, fallback = '') => { try { return sh(cmd); } catch { return fallback; } };

function branchTip(ref) {
  const line = shSafe(`git log -1 --format=%h%s ${ref} --`, '');
  if (!line) return null;
  const [hash, subject] = line.split('');
  return { hash, subject };
}

function countBetween(a, b) {
  const n = shSafe(`git rev-list --count ${a}..${b}`, '');
  return /^\d+$/.test(n) ? parseInt(n, 10) : null;
}

function syncDescription(main, staging) {
  if (!main || !staging) return 'unknown (a branch is missing locally — run `git fetch`)';
  if (main.hash === staging.hash) return `staging and main in sync at \`${main.hash}\``;
  const ahead  = countBetween('main', 'staging'); // staging-only commits
  const behind = countBetween('staging', 'main'); // main-only commits
  if (ahead && !behind)  return `staging is ahead of main by ${ahead} commit(s)`;
  if (behind && !ahead)  return `main is ahead of staging by ${behind} commit(s)`;
  if (ahead && behind)   return `**diverged** — staging +${ahead} / main +${behind} (see [[fieldops_prod_deploy_cherrypick]] deploy model)`;
  return 'staging and main differ';
}

function appVersion() {
  try {
    const html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
    const m = html.match(/window\.APP_VERSION\s*=\s*'([^']+)'/);
    return m ? m[1] : 'unknown';
  } catch { return 'unknown'; }
}

function buildSections() {
  const today    = new Date().toISOString().slice(0, 10);
  const curBranch= shSafe('git rev-parse --abbrev-ref HEAD', '?');
  const main     = branchTip('main');
  const staging  = branchTip('staging');
  const tag      = shSafe('git describe --tags --abbrev=0', '(none)');
  const dirty    = shSafe('git status --porcelain');
  const treeState= dirty ? `${dirty.split('\n').filter(Boolean).length} uncommitted change(s)` : 'clean';

  const lastVerified =
`## Last verified

- **Snapshot timestamp:** ${today} — generated by \`scripts/update-state.cjs\`
- **Snapshot author:** \`scripts/update-state.cjs\` (deterministic git snapshot; replaces the retired automation-memory-agent for mechanical fields)
- **Generated from branch:** \`${curBranch}\`
`;

  const branchCommit =
`## Branch + commit

- **Canonical branch:** \`main\`
- **Latest commit on \`main\`:** ${main ? `\`${main.hash}\` — ${main.subject}` : '_(not found locally — run `git fetch`)_'}
- **Latest commit on \`staging\`:** ${staging ? `\`${staging.hash}\` — ${staging.subject}` : '_(not found locally — run `git fetch`)_'}
- **Branch sync:** ${syncDescription(main, staging)}
- **Latest git tag:** \`${tag}\`
- **App version (\`index.html\`):** \`${appVersion()}\`
- **Working tree (when generated):** ${treeState}
`;

  return { lastVerified, branchCommit };
}

/** Replace the body of a `## Header` section, up to the next horizontal rule (`---`). */
function replaceSection(md, header, newBody) {
  // Matches "## Header" ... up to (but not including) the next line that is just "---".
  const re = new RegExp(`(^|\\n)## ${header}\\n[\\s\\S]*?(?=\\n---\\n)`, 'm');
  if (!re.test(md)) {
    throw new Error(`Section "## ${header}" not found in STATE.md — aborting to avoid corrupting the file.`);
  }
  // newBody already starts with "## Header" and ends with a single newline; the
  // captured remainder begins at "\n---", so keeping that trailing newline yields
  // a blank line before the rule (avoids "text\n---" rendering as a setext heading).
  return md.replace(re, (m, lead) => `${lead}${newBody}`);
}

function main() {
  const check = process.argv.includes('--check');
  const orig  = fs.readFileSync(STATE_FILE, 'utf8');
  const { lastVerified, branchCommit } = buildSections();

  let next = orig;
  next = replaceSection(next, 'Last verified', lastVerified);
  next = replaceSection(next, 'Branch \\+ commit', branchCommit);

  if (next === orig) {
    console.log('STATE.md already up to date — no changes.');
    return;
  }
  if (check) {
    console.log('--check: STATE.md WOULD be updated. New mechanical sections:\n');
    console.log(lastVerified + '\n' + branchCommit);
    return;
  }
  fs.writeFileSync(STATE_FILE, next, 'utf8');
  console.log('Updated automation/STATE.md (Last verified + Branch + commit).');
  console.log('Narrative sections (shipped tables, Supabase notes) left untouched — edit those manually.');
}

main();
